name: Build quicksample
on: [push, pull_request]
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libjack-jackd2-dev \
            ladspa-sdk libcurl4-openssl-dev libfreetype6-dev \
            libx11-dev libxcomposite-dev libxcursor-dev \
            libxext-dev libxinerama-dev libxrandr-dev \
            libxrender-dev libwebkit2gtk-4.1-dev libglu1-mesa-dev
    
    - name: Install WebView2 SDK (Windows)
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest -Uri "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile "nuget.exe"
        
        .\nuget.exe install Microsoft.Web.WebView2 -OutputDirectory packages
        
        Get-ChildItem packages
    
    - name: Install NSIS (Windows)
      if: runner.os == 'Windows'
      run: choco install nsis
    
    - name: Configure (Windows)
      if: runner.os == 'Windows'
      run: cmake -B build -A x64 -DCMAKE_BUILD_TYPE=Release
    
    - name: Configure (Linux)
      if: runner.os == 'Linux'
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Package
      run: |
        cd build
        cpack -C Release
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quicksample-${{ runner.os }}
        path: |
          build/*.zip
          build/*.deb
          build/*.tar.gz
          build/*.exe 